url: "https://thisisnotculture.us"
description: this is everything
baseurl: ""
title: everything
copyright: scott kilts
email: sjkilts@gmail.com
permalink: /:categories/:title/

plugins:
  - jekyll-sitemap

excerpt_separator: <!--more-->

users:
  - login: "sjkilts"
    user: "Scott Kilts"

include: 
  - _notes
  
collections:
  notes:
    output: true  
  
site_tree.file: map.md
  
prose:
  siteurl: "https://thisisnotculture.us"
  media: "/media"
  metadata:
    _posts:
      - name: "title"
        field:
        element: "text"
        label: "title"
      - name: "published"
        field: 
          element: "button"
          label: "published"
          on: "true"
          off: "false"
      - name: "img"
        field:
          element: "text"
          label: "image"
          placeholder: "/media/imagename.png"
      - name: "img-name"
        field:
          element: "text"
          label:  "image name"
          placeholder: "image name"
      - name: "medium"
        field:
          element: "text"
          label:  "medium"
          placeholder: "medium"
      - name: "title"
        field:
          element: "text"
          label:  "title"
          placeholder: "title"
      - name: "content"
        field:
          element: "textarea"
          label: "post content"
          placeholder: "text for post"
    _notes/projects:
      - name: "title"
        field:
         element: "text"
         label: "title"
      - name: "project"
        field: 
          element: "text"
          label: "project"
          placeholder: "project name"
      - name: "client"
        field: 
          element: "multiselect"
          label: "client"
          placeholder: "select client"
          options: 
            - tenants union
            - scott j kilts
            - this is not culture
            - spacetimedistortion
            - wave
            - free the land
            - ultralightlife
            - jupiter card
      - name: "description"
        field: 
          element: "text"
          label: "description"
          placeholder: "project description"
    _notes/hours:
      - name: "title"
        field:
          element: "text"
          label: "title"
